services:
  fastapi_app:
    build: .
    container_name: fastapi_google_sheet_to_xml
    restart: always
    environment:
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
      - TOKEN_JSON=${TOKEN_JSON}
    ports:
      - "8080:8080"
    volumes:
      - ./httpdocs/XML_prices/google_sheet_to_xml:/httpdocs/XML_prices/google_sheet_to_xml