replicaCount: 1
image:
  repository: your-docker-username/xml-app
  pullPolicy: Always
  tag: "v0.1.2-8f85292"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
env:
  # Базові змінні
  GOOGLE_CREDENTIALS:
    secretName: google-secrets
    secretKey: google-xml-secrets
  TOKEN_JSON:
    secretName: google-secrets
    secretKey: token-json
  # Додаткові змінні можна додавати у форматі:
  # НАЗВА_ЗМІННОЇ: "значення"
  # Наприклад:
  # DEBUG: "true"
  # API_KEY: "your-api-key"
