apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xml-app.fullname" . }}
  labels:
    {{- include "xml-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "xml-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xml-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              {{- if kindIs "map" $value }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.secretKey }}
              {{- else }}
              value: {{ $value | quote }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: xml-storage
              mountPath: /app/output
      volumes:
        - name: xml-storage
          persistentVolumeClaim:
            claimName: {{ include "xml-app.fullname" . }}-pvc
