name: Deploy Docker Container

on:
  push:
    branches:
      - develop  # Запускати деплой при пуші в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Клонування репозиторію
      uses: actions/checkout@v3

    - name: 🔑 Логін у Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || exit 1


    - name: 🛠 Створення `.env` з GitHub Secrets
      run: |
        echo 'GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS }}' > .env
        echo 'TOKEN_JSON=${{ secrets.TOKEN_JSON }}' >> .env

    - name: 📦 Побудова Docker-образу
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/xml-app:latest .

    - name: 🚀 Публікація Docker-образу в Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/xml-app:latest

    - name: 🛠 Видалення старого контейнера (якщо існує)
      run: |
        docker stop xml_container || true
        docker rm xml_container || true

    - name: 🚀 Запуск нового контейнера
      run: |
        docker run -d --name xml_container \
          --env-file .env \
          -p 8000:8000 \
          ${{ secrets.DOCKER_USERNAME }}/xml-app:latest
