name: Release Docker Container with versions
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: 📥 Клонування репозиторію
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🔍 Отримання версії з тега
        id: set_version
        run: |
          VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: 🔑 Логін у Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: 📦 Побудова та пуш Docker-образу
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/xml-app:${{ steps.set_version.outputs.version }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/xml-app:${{ steps.set_version.outputs.version }}
  update_chart:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      VERSION: ${{ needs.build_and_push.outputs.version }}
    steps:
      - name: 📥 Клонування репозиторію (main)
        uses: actions/checkout@v4
        with:
          ref: helm
          fetch-depth: 0
      - name: 🔼 Оновлення версії Helm-чарту (+1)
        run: |
          CHART_VERSION=$(yq '.version' xml-app/Chart.yaml)
          NEW_VERSION=$(echo $CHART_VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
          yq -i ".version=\"$NEW_VERSION\"" xml-app/Chart.yaml
      - name: 🔄 Оновлення тега образу в `values.yaml`
        run: yq -i ".image.tag=\"${{ env.VERSION }}\"" xml-app/values.yaml
      - name: 📝 Коміт оновленого Helm-чарту в helm
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add xml-app/Chart.yaml xml-app/values.yaml
          git commit -m "🔄 Оновлення Helm-чарту: версія $NEW_VERSION, образ $VERSION"
          git push origin helm